"""Criar tabelas de categorias e produtos2

Revision ID: 3c6d0278d1b9
Revises: 5de3c721c68f
Create Date: 2026-05-29 13:18:03.218649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6d0278d1b9'
down_revision: Union[str, Sequence[str], None] = '5de3c721c68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('produtos', sa.Column('preco', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('produtos', 'preco')
    # ### end Alembic commands ###
